configs:
  - name: test1
    config: -DCMAKE_BUILD_TYPE=Debug -DBUILD_META_EXAMPLES=ON -DENABLE_ASAN=ON -DENABLE_MSAN=ON -DENABLE_TSAN=ON -DENABLE_UBSAN=ON
  - name: test2
    config: -DCMAKE_BUILD_TYPE=Debug -DBUILD_META_EXAMPLES=ON